Repository Liberty52/product, pull requests merged in 2023-11, with the labels that each got.

#345 라이선스 옵션 상세 이슈 해결
  src/main/java/com/liberty52/product/service/applicationservice/impl/LicenseOptionCreateServiceImpl.java
  src/main/java/com/liberty52/product/service/controller/license/LicenseOptionDetailController.java
  src/main/java/com/liberty52/product/service/controller/license/LicenseProductInfoController.java
Labels: 🐞 BugFix

#346 상품과 라이선스 옵션 간 cascade 설정 변경
  src/main/java/com/liberty52/product/service/applicationservice/impl/LicenseOptionCreateServiceImpl.java
  src/main/java/com/liberty52/product/service/entity/Product.java
  src/main/java/com/liberty52/product/service/entity/license/LicenseOption.java
  src/test/java/com/liberty52/product/service/applicationservice/mock/LicenseOptionCreateMockTest.java
Labels: 🐞 BugFix

#347 fix: 스마트택배 프로토콜 변경 (http -> https)
  src/main/java/com/liberty52/product/global/adapter/courier/config/CourierUrl.java
Labels: 🐞 BugFix

#350 [관리자] 라이선스 상품 상세 옵션 필드 추가(시작일,종료일)
  src/main/java/com/liberty52/product/service/applicationservice/impl/LicenseOptionDetailCreateServiceImpl.java
  src/main/java/com/liberty52/product/service/applicationservice/impl/LicenseOptionDetailModifyServiceImpl.java
  src/main/java/com/liberty52/product/service/applicationservice/impl/LicenseProductInfoRetrieveServiceImpl.java
  src/main/java/com/liberty52/product/service/controller/dto/LicenseOptionDetailCreateDto.java
  src/main/java/com/liberty52/product/service/controller/dto/LicenseOptionDetailInfoResponseDto.java
  src/main/java/com/liberty52/product/service/controller/dto/LicenseOptionDetailModifyDto.java
  src/main/java/com/liberty52/product/service/controller/dto/LicenseOptionInfoResponseDto.java
  src/main/java/com/liberty52/product/service/controller/dto/LicenseOptionResponseDto.java
  src/main/java/com/liberty52/product/service/entity/license/LicenseOptionDetail.java
  src/test/java/com/liberty52/product/service/applicationservice/mock/LicenseOptionDetailCreateMockTest.java
  src/test/java/com/liberty52/product/service/applicationservice/mock/LicenseOptionDetailModifyMockTest.java
  src/test/java/com/liberty52/product/service/applicationservice/mock/LicenseProductInfoRetrieveMockTest.java
Labels: ✨ Feature, 🔗 API

#352 Liberty Authentication Module 추가
  build.gradle
  liberty-authentication-library/build.gradle
  liberty-authentication-library/gradle/wrapper/gradle-wrapper.jar
  liberty-authentication-library/gradle/wrapper/gradle-wrapper.properties
  liberty-authentication-library/settings.gradle
  liberty-authentication-library/src/main/java/com/liberty52/authentication/annotation/LBPreAuthorize.java
  liberty-authentication-library/src/main/java/com/liberty52/authentication/annotation/UserContext.java
  liberty-authentication-library/src/main/java/com/liberty52/authentication/core/Authentication.java
  liberty-authentication-library/src/main/java/com/liberty52/authentication/core/UserRole.java
  liberty-authentication-library/src/main/java/com/liberty52/authentication/core/context/AuthenticationContext.java
  liberty-authentication-library/src/main/java/com/liberty52/authentication/core/context/AuthenticationContextHolder.java
  liberty-authentication-library/src/main/java/com/liberty52/authentication/core/context/AuthenticationContextHolderStrategy.java
  liberty-authentication-library/src/main/java/com/liberty52/authentication/core/context/AuthenticationContextImpl.java
  liberty-authentication-library/src/main/java/com/liberty52/authentication/core/context/ThreadLocalAuthenticationContextHolderStrategy.java
  liberty-authentication-library/src/main/java/com/liberty52/authentication/core/exception/AuthenticationError.java
  liberty-authentication-library/src/main/java/com/liberty52/authentication/core/exception/AuthenticationException.java
  liberty-authentication-library/src/main/java/com/liberty52/authentication/core/principal/AbstractUser.java
  liberty-authentication-library/src/main/java/com/liberty52/authentication/core/principal/AnonymousUser.java
  liberty-authentication-library/src/main/java/com/liberty52/authentication/core/principal/AuthUser.java
  liberty-authentication-library/src/main/java/com/liberty52/authentication/core/principal/GuestUser.java
  liberty-authentication-library/src/main/java/com/liberty52/authentication/core/principal/User.java
  liberty-authentication-library/src/main/java/com/liberty52/authentication/core/token/AbstractAuthenticationToken.java
  liberty-authentication-library/src/main/java/com/liberty52/authentication/core/token/AnonymousAuthenticationToken.java
  liberty-authentication-library/src/main/java/com/liberty52/authentication/core/token/AuthenticationTokenUtils.java
  liberty-authentication-library/src/main/java/com/liberty52/authentication/core/token/UserAuthenticationToken.java
  liberty-authentication-library/src/main/java/com/liberty52/authentication/test/configurer/web/LBWebMvcTest.java
  liberty-authentication-library/src/main/java/com/liberty52/authentication/test/context/TestAuthenticationContextHolder.java
  liberty-authentication-library/src/main/java/com/liberty52/authentication/test/context/TestAuthenticationContextHolderStrategyAdapter.java
  liberty-authentication-library/src/main/java/com/liberty52/authentication/test/context/support/AuthenticationTestExecutionListeners.java
  liberty-authentication-library/src/main/java/com/liberty52/authentication/test/context/support/LBTestExecutionEvent.java
  liberty-authentication-library/src/main/java/com/liberty52/authentication/test/context/support/WithAuthenticationContext.java
  liberty-authentication-library/src/main/java/com/liberty52/authentication/test/context/support/WithAuthenticationContextFactory.java
  liberty-authentication-library/src/main/java/com/liberty52/authentication/test/context/support/WithAuthenticationContextTestExecutionListener.java
  liberty-authentication-library/src/main/java/com/liberty52/authentication/test/context/support/WithLBMockUser.java
  liberty-authentication-library/src/main/java/com/liberty52/authentication/test/context/support/WithLBMockUserAuthenticationFactory.java
  liberty-authentication-library/src/main/java/com/liberty52/authentication/web/aspect/LBPreAuthorizeAspect.java
  liberty-authentication-library/src/main/java/com/liberty52/authentication/web/configurer/AuthenticationAspectConfiguration.java
  liberty-authentication-library/src/main/java/com/liberty52/authentication/web/configurer/AuthenticationWebConfiguration.java
  liberty-authentication-library/src/main/java/com/liberty52/authentication/web/filter/AuthenticationFilter.java
  liberty-authentication-library/src/main/java/com/liberty52/authentication/web/resolver/UserContextArgumentResolver.java
  liberty-authentication-library/src/main/resources/application.properties
  settings.gradle
  src/main/java/com/liberty52/product/ProductApplication.java
  src/main/java/com/liberty52/product/global/config/WebConfig.java
  src/main/java/com/liberty52/product/global/exception/external/ErrorResponse.java
  src/main/java/com/liberty52/product/global/exception/external/ProductErrorCode.java
  src/main/java/com/liberty52/product/global/exception/external/RestExceptionHandler.java
  src/main/java/com/liberty52/product/global/exception/external/unauthorized/UnauthorizedException.java
  src/main/java/com/liberty52/product/service/controller/OrderAdminController.java
  src/test/java/com/liberty52/product/service/controller/OrderAdminControllerTest.java
Labels: 🔨 Refactor

#360 장바구니 배송비 조회 추가
  src/main/java/com/liberty52/product/service/applicationservice/impl/CartItemRetrieveServiceImpl.java
  src/main/java/com/liberty52/product/service/controller/dto/CartItemResponse.java
  src/main/java/com/liberty52/product/service/entity/license/LicenseOption.java
  src/test/java/com/liberty52/product/service/applicationservice/mock/CartItemRetrieveServiceMockTest.java
Labels: ✨ Feature, 🔗 API

#361 [관리자] 라이선스 상품 옵션 생성 예외 추가
  src/main/java/com/liberty52/product/service/applicationservice/impl/LicenseOptionCreateServiceImpl.java
  src/main/java/com/liberty52/product/service/controller/license/LicenseProductInfoController.java
  src/main/java/com/liberty52/product/service/repository/LicenseOptionRepository.java
  src/test/java/com/liberty52/product/service/applicationservice/mock/LicenseOptionCreateMockTest.java
Labels: 🐞 BugFix

#362 라이선스 상품 주문 생성
  src/main/java/com/liberty52/product/service/applicationservice/impl/LicenseOptionDetailModifyServiceImpl.java
  src/main/java/com/liberty52/product/service/applicationservice/impl/OrderCreateServiceImpl.java
  src/main/java/com/liberty52/product/service/applicationservice/impl/OrderStatusModifyServiceImpl.java
  src/main/java/com/liberty52/product/service/controller/OrderController.java
  src/main/java/com/liberty52/product/service/controller/dto/LicenseOptionDetailInfoResponseDto.java
  src/main/java/com/liberty52/product/service/controller/dto/OrderDetailRetrieveResponse.java
  src/main/java/com/liberty52/product/service/controller/dto/OrderRetrieveProductResponse.java
  src/main/java/com/liberty52/product/service/controller/dto/OrdersRetrieveResponse.java
  src/main/java/com/liberty52/product/service/controller/license/LicenseOptionDetailAdminController.java
  src/main/java/com/liberty52/product/service/entity/CustomProduct.java
  src/main/java/com/liberty52/product/service/entity/Orders.java
  src/main/java/com/liberty52/product/service/entity/Product.java
  src/main/java/com/liberty52/product/service/entity/license/CustomLicenseOption.java
  src/main/java/com/liberty52/product/service/entity/license/LicenseOption.java
  src/main/java/com/liberty52/product/service/entity/license/LicenseOptionDetail.java
  src/main/java/com/liberty52/product/service/repository/CustomLicenseOptionRepository.java
  src/test/java/com/liberty52/product/service/applicationservice/impl/OrderCreateServiceImplUnitTest.java
  src/test/java/com/liberty52/product/service/applicationservice/mock/LicenseOptionDetailModifyMockTest.java
  src/test/java/com/liberty52/product/service/utils/MockFactory.java
Labels: ✨ Feature, 🔗 API, 📦 Database

#380 상품, 커스텀 상품 삭제관련 참조관계 설정 조정
  src/main/java/com/liberty52/product/service/applicationservice/impl/ProductRemoveServiceImpl.java
  src/main/java/com/liberty52/product/service/entity/Product.java
  src/main/java/com/liberty52/product/service/entity/ProductOption.java
  src/main/java/com/liberty52/product/service/repository/CustomProductRepository.java
Labels: 🔨 Refactor

#378 매출액, 판매량 동적 조회
  src/main/java/com/liberty52/product/service/applicationservice/SalesRetrieveService.java
  src/main/java/com/liberty52/product/service/applicationservice/impl/SalesRetrieveServiceImpl.java
  src/main/java/com/liberty52/product/service/controller/SalesAdminController.java
  src/main/java/com/liberty52/product/service/controller/dto/SalesRequestDto.java
  src/main/java/com/liberty52/product/service/controller/dto/SalesResponseDto.java
  src/main/java/com/liberty52/product/service/repository/OrderQueryDslRepository.java
  src/main/java/com/liberty52/product/service/repository/OrderQueryDslRepositoryImpl.java
  src/test/java/com/liberty52/product/service/applicationservice/SalesRetrieveServiceImplTest.java
Labels: ✨ Feature, 🔗 API

#388 엔드포인트 / 추가
  liberty-main/src/main/java/com/liberty52/main/service/controller/SalesAdminController.java
Labels: 🛠 Chore

#383 라이선스 상품 장바구니 추가
  liberty-main/src/main/java/com/liberty52/main/service/applicationservice/impl/CartItemCreateServiceImpl.java
  liberty-main/src/main/java/com/liberty52/main/service/controller/CartItemController.java
  liberty-main/src/main/java/com/liberty52/main/service/controller/guest/CartItemGuestController.java
  liberty-main/src/main/java/com/liberty52/main/service/entity/CustomProductOption.java
  liberty-main/src/test/java/com/liberty52/main/service/applicationservice/mock/CartItemCreateServiceMockTest.java
  liberty-main/src/test/java/com/liberty52/main/service/applicationservice/mock/CartLicenseItemCreateServiceMockTest.java
Labels: ✨ Feature, 🔗 API

#384 라이선스 상품 장바구니 조회
  liberty-main/src/main/java/com/liberty52/main/service/applicationservice/impl/CartItemRetrieveServiceImpl.java
  liberty-main/src/main/java/com/liberty52/main/service/controller/dto/CartItemResponse.java
Labels: ✨ Feature, 🔗 API

#386 장바구니 수정 관련 요소 추가
  liberty-main/src/main/java/com/liberty52/main/service/applicationservice/impl/CartItemModifyServiceImpl.java
  liberty-main/src/main/java/com/liberty52/main/service/controller/dto/ProductInfoByCartResponseDto.java
Labels: ✨ Feature, 🔗 API

#403 `ISSUE-#402` fix: OrderGuestController @CrossOrigin 삭제
  liberty-main/src/main/java/com/liberty52/main/service/controller/guest/OrderGuestController.java
Labels: 🔗 API, 🐞 BugFix

#401 라이선스 상품 주문 관련 로직 변경
  liberty-main-service/src/main/java/com/liberty52/main/service/applicationservice/LicenseOptionDetailStockManageService.java
  liberty-main-service/src/main/java/com/liberty52/main/service/applicationservice/OptionDetailMultipleStockManageService.java
  liberty-main-service/src/main/java/com/liberty52/main/service/applicationservice/impl/LicenseOptionDetailStockManageServiceImpl.java
  liberty-main-service/src/main/java/com/liberty52/main/service/applicationservice/impl/OptionDetailMultipleStockManageServiceImpl.java
  liberty-main-service/src/main/java/com/liberty52/main/service/applicationservice/impl/OrderCreateServiceImpl.java
  liberty-main-service/src/main/java/com/liberty52/main/service/applicationservice/impl/OrderFailedPayRollbackServiceImpl.java
  liberty-main-service/src/main/java/com/liberty52/main/service/entity/license/LicenseOptionDetail.java
  liberty-main-service/src/test/java/com/liberty52/main/service/applicationservice/impl/OrderCreateServiceImplUnitTest.java
Labels: ✨ Feature

#423 라이선스 상품 구매 시 옵션 및 라이선스 옵션 둘 다 받을 수 있게 수정
  liberty-main-service/src/main/java/com/liberty52/main/service/applicationservice/OptionDetailMultipleStockManageService.java
  liberty-main-service/src/main/java/com/liberty52/main/service/applicationservice/impl/OptionDetailMultipleStockManageServiceImpl.java
  liberty-main-service/src/main/java/com/liberty52/main/service/applicationservice/impl/OrderCreateServiceImpl.java
  liberty-main-service/src/main/java/com/liberty52/main/service/controller/dto/OrderCreateRequestDto.java
  liberty-main-service/src/test/java/com/liberty52/main/service/applicationservice/OrderCreateServiceImplTest.java
  liberty-main-service/src/test/java/com/liberty52/main/service/applicationservice/impl/CanceledOrderRetrieveTest.java
  liberty-main-service/src/test/java/com/liberty52/main/service/applicationservice/impl/OrderCancelServiceImplTest.java
  liberty-main-service/src/test/java/com/liberty52/main/service/applicationservice/impl/OrderCreateServiceImplUnitTest.java
  liberty-main-service/src/test/java/com/liberty52/main/service/controller/OrderControllerTest.java
  liberty-main-service/src/test/java/com/liberty52/main/service/entity/OrdersEntityTest.java
Labels: ✨ Feature

#424 fix: 주문 시 라이센스 이미지 required 변경
  liberty-main-service/src/main/java/com/liberty52/main/service/controller/guest/OrderGuestController.java
Labels: 🐞 BugFix
