Repository Liberty52/product, pull requests merged in 2023-09, with the labels that each got.

#233 상품 정보 조회시 상품 소개 이미지 같이 조회
  src/main/java/com/liberty52/product/service/applicationservice/impl/ProductInfoRetrieveServiceImpl.java
  src/main/java/com/liberty52/product/service/controller/dto/ProductDetailResponseDto.java
  src/main/java/com/liberty52/product/service/controller/dto/ProductInfoRetrieveResponseDto.java
  src/test/java/com/liberty52/product/service/applicationservice/ProductInfoRetrieveServiceTest.java
Labels: feature

#229 Fix 222
  src/main/java/com/liberty52/product/service/applicationservice/impl/CartItemRetrieveServiceImpl.java
  src/main/java/com/liberty52/product/service/controller/dto/CartItemRequest.java
  src/test/java/com/liberty52/product/MockS3Test.java
  src/test/java/com/liberty52/product/service/applicationservice/mock/CartItemCreateServiceMockTest.java
  src/test/java/com/liberty52/product/service/applicationservice/mock/CartItemRetrieveServiceMockTest.java
  src/test/java/com/liberty52/product/service/applicationservice/mock/CartItemSchedulerServiceMockTest.java
Labels: refactor, fix, test

#230 (관리자) 상품 소개 관리 수정
  src/main/java/com/liberty52/product/service/applicationservice/ProductIntroductionModifyService.java
  src/main/java/com/liberty52/product/service/applicationservice/impl/ProductIntroductionModifyServiceImpl.java
  src/main/java/com/liberty52/product/service/controller/ProductIntroductionModifyController.java
  src/test/java/com/liberty52/product/service/applicationservice/mock/ProductIntroductionModifyMockTest.java
Labels: ✨ Feature

#236 feat: 상품 소개 추가 예외 처리
  src/main/java/com/liberty52/product/service/applicationservice/impl/ProductIntroductionCreateServiceImpl.java
  src/test/java/com/liberty52/product/service/applicationservice/mock/ProductIntroductionCreateMockTest.java
Labels: 🐞 BugFix

#247 [관리자] 상품 옵션 선택지 재고량 수정 기능
  src/main/java/com/liberty52/product/global/config/DBInitConfig.java
  src/main/java/com/liberty52/product/service/applicationservice/impl/OptionDetailCreateServiceImpl.java
  src/main/java/com/liberty52/product/service/applicationservice/impl/OptionDetailModifyServiceImpl.java
  src/main/java/com/liberty52/product/service/controller/dto/CreateOptionDetailRequestDto.java
  src/main/java/com/liberty52/product/service/controller/dto/OptionDetailModifyRequestDto.java
  src/main/java/com/liberty52/product/service/controller/dto/ProductOptionDetailResponseDto.java
  src/main/java/com/liberty52/product/service/entity/OptionDetail.java
  src/test/java/com/liberty52/product/service/applicationservice/OptionDetailModifyServiceTest.java
  src/test/java/com/liberty52/product/service/applicationservice/mock/CartItemCreateServiceMockTest.java
  src/test/java/com/liberty52/product/service/applicationservice/mock/CartItemRetrieveServiceMockTest.java
  src/test/java/com/liberty52/product/service/applicationservice/mock/CartItemSchedulerServiceMockTest.java
  src/test/java/com/liberty52/product/service/applicationservice/mock/OptionDetailModifyServiceMockTest.java
  src/test/java/com/liberty52/product/service/utils/MockFactory.java
Labels: ✨ Feature, 🔗 API, 🔨 Refactor
