Repository Liberty52/product, pull requests merged in 2023-10, with the labels that each got.

#254 상품 옵션 조회시 재고량 조회 빠진 부분 추가
  src/main/java/com/liberty52/product/service/controller/dto/ProductDetailResponseDto.java
  src/test/java/com/liberty52/product/service/applicationservice/ProductInfoRetrieveServiceTest.java
Labels: ✨ Feature

#258 feat:관리자는 이미지를 업스케일(upscaling)한다.
  src/main/java/com/liberty52/product/global/adapter/ImageUpscaler.java
  src/main/java/com/liberty52/product/global/adapter/StableDiffusionApi.java
  src/main/java/com/liberty52/product/global/util/Result.java
  src/main/java/com/liberty52/product/service/applicationservice/ImageUpscalingService.java
  src/main/java/com/liberty52/product/service/applicationservice/impl/ImageUpscalingServiceImpl.java
  src/main/java/com/liberty52/product/service/controller/ImageUpscalingController.java
  src/main/java/com/liberty52/product/service/controller/dto/ImageUpscalingDto.java
  src/test/java/com/liberty52/product/global/adapter/StableDiffusionApiTest.java
  src/test/java/com/liberty52/product/service/applicationservice/impl/ImageUpscalingServiceImplTest.java
  src/test/java/com/liberty52/product/service/controller/ImageUpscalingControllerTest.java
Labels: ✨ Feature

#253 [SPRINT 2] 상품 구매 시 재고량 감소 기능 추가
  gradlew
  src/main/java/com/liberty52/product/global/util/ThreadManager.java
  src/main/java/com/liberty52/product/global/util/_ThreadManager.java
  src/main/java/com/liberty52/product/service/applicationservice/impl/OrderCreateServiceImpl.java
  src/main/java/com/liberty52/product/service/entity/OptionDetail.java
  src/main/java/com/liberty52/product/service/entity/payment/CardPayment.java
  src/test/java/com/liberty52/product/service/applicationservice/CartItemRemoveServiceImplTest.java
  src/test/java/com/liberty52/product/service/applicationservice/ReviewCreateServiceImplTest.java
  src/test/java/com/liberty52/product/service/applicationservice/impl/OrderCreateServiceImplUnitTest.java
  src/test/java/com/liberty52/product/service/utils/MockFactory.java
Labels: ✨ Feature, 🔨 Refactor

#265 [관리자] 라이센스 이미지 수정,삭제
  src/main/java/com/liberty52/product/service/applicationservice/LicenseImageDeleteService.java
  src/main/java/com/liberty52/product/service/applicationservice/LicenseImageModifyService.java
  src/main/java/com/liberty52/product/service/applicationservice/impl/LicenseImageCreateServiceImpl.java
  src/main/java/com/liberty52/product/service/applicationservice/impl/LicenseImageDeleteServiceImpl.java
  src/main/java/com/liberty52/product/service/applicationservice/impl/LicenseImageModifyServiceImpl.java
  src/main/java/com/liberty52/product/service/controller/LicenseImageDeleteController.java
  src/main/java/com/liberty52/product/service/controller/LicenseImageModifyController.java
  src/main/java/com/liberty52/product/service/controller/dto/LicenseImageModifyDto.java
  src/main/java/com/liberty52/product/service/entity/LicenseImage.java
  src/test/java/com/liberty52/product/service/applicationservice/mock/LicenseImageDeleteMockTest.java
  src/test/java/com/liberty52/product/service/applicationservice/mock/LicenseImageModifyMockTest.java
Labels: ✨ Feature, 🔗 API

#263 fix: ObjectMapper 기본생성자 요구 모듈 추가
  src/main/java/com/liberty52/product/global/config/BeanConfig.java
  src/main/java/com/liberty52/product/global/config/JacksonConfig.java
  src/main/java/com/liberty52/product/service/entity/payment/VBankPayment.java
Labels: 🐞 BugFix

#278 라이센스 이미지 상세 조회 추가
  src/main/java/com/liberty52/product/service/applicationservice/LicenseImageRetrieveService.java
  src/main/java/com/liberty52/product/service/applicationservice/impl/LicenseImageRetrieveServiceImpl.java
  src/main/java/com/liberty52/product/service/controller/LicenseImageRetrieveController.java
  src/test/java/com/liberty52/product/service/applicationservice/mock/LicenseImageRetrieveMockTest.java
Labels: ✨ Feature, 🔗 API

#285 주문 요청 시 옵션명이 아닌 옵션 ID로 요청하도록 API 수정
  src/main/java/com/liberty52/product/global/config/DBInitConfig.java
  src/main/java/com/liberty52/product/service/applicationservice/impl/OrderCreateServiceImpl.java
  src/main/java/com/liberty52/product/service/controller/dto/OrderCreateRequestDto.java
  src/test/java/com/liberty52/product/service/applicationservice/OrderCreateServiceImplTest.java
  src/test/java/com/liberty52/product/service/applicationservice/impl/CanceledOrderRetrieveTest.java
  src/test/java/com/liberty52/product/service/applicationservice/impl/OrderCreateServiceImplUnitTest.java
  src/test/java/com/liberty52/product/service/entity/OrdersEntityTest.java
Labels: 🔗 API

#287 [Refactor] 옵션상세(optionDetail) , 상품정보 , 상품옵션(option) 컨트롤러 통합
  src/main/java/com/liberty52/product/service/controller/OptionDetailController.java
  src/main/java/com/liberty52/product/service/controller/OptionDetailCreateController.java
  src/main/java/com/liberty52/product/service/controller/ProductInfoController.java
  src/main/java/com/liberty52/product/service/controller/ProductIntroductionCreateController.java
  src/main/java/com/liberty52/product/service/controller/ProductIntroductionModifyController.java
  src/main/java/com/liberty52/product/service/controller/ProductOptionController.java
  src/main/java/com/liberty52/product/service/controller/ProductOptionCreateController.java
Labels: 🔨 Refactor

#290 refactor: Result
  src/main/java/com/liberty52/product/global/adapter/StableDiffusionApi.java
  src/main/java/com/liberty52/product/global/util/Result.java
Labels: 🔨 Refactor

#295 Product 엔티티 - 라이선스 적용 상품인지 구분 위한 isCustom 속성 추가
  src/main/java/com/liberty52/product/global/config/DBInitConfig.java
  src/main/java/com/liberty52/product/service/entity/Product.java
  src/test/java/com/liberty52/product/service/applicationservice/CartItemRemoveServiceImplTest.java
  src/test/java/com/liberty52/product/service/applicationservice/ReviewCreateServiceImplTest.java
  src/test/java/com/liberty52/product/service/applicationservice/mock/CartItemCreateServiceMockTest.java
  src/test/java/com/liberty52/product/service/applicationservice/mock/CartItemRetrieveServiceMockTest.java
  src/test/java/com/liberty52/product/service/applicationservice/mock/CartItemSchedulerServiceMockTest.java
  src/test/java/com/liberty52/product/service/utils/MockFactory.java
Labels: 🔨 Refactor

#292 이미지, 라이센스 이미지, 리뷰, 배달옵션 컨트롤러 통합
  src/main/java/com/liberty52/product/service/controller/DeliveryOptionController.java
  src/main/java/com/liberty52/product/service/controller/DeliveryOptionModifyController.java
  src/main/java/com/liberty52/product/service/controller/DeliveryOptionRetrieveController.java
  src/main/java/com/liberty52/product/service/controller/ImageController.java
  src/main/java/com/liberty52/product/service/controller/ImageGenerationController.java
  src/main/java/com/liberty52/product/service/controller/ImageUpscalingController.java
  src/main/java/com/liberty52/product/service/controller/LicenseImageController.java
  src/main/java/com/liberty52/product/service/controller/LicenseImageCreateController.java
  src/main/java/com/liberty52/product/service/controller/LicenseImageDeleteController.java
  src/main/java/com/liberty52/product/service/controller/LicenseImageModifyController.java
  src/main/java/com/liberty52/product/service/controller/LicenseImageRetrieveController.java
  src/main/java/com/liberty52/product/service/controller/ReviewController.java
  src/main/java/com/liberty52/product/service/controller/ReviewCreateController.java
  src/main/java/com/liberty52/product/service/controller/ReviewModifyController.java
  src/main/java/com/liberty52/product/service/controller/ReviewRemoveController.java
  src/main/java/com/liberty52/product/service/controller/ReviewReplyController.java
  src/main/java/com/liberty52/product/service/controller/ReviewReplyCreateController.java
  src/main/java/com/liberty52/product/service/controller/ReviewReplyModifyController.java
  src/main/java/com/liberty52/product/service/controller/ReviewRetrieveController.java
  src/test/java/com/liberty52/product/service/controller/DeliveryOptionControllerTest.java
  src/test/java/com/liberty52/product/service/controller/DeliveryOptionModifyControllerTest.java
  src/test/java/com/liberty52/product/service/controller/DeliveryOptionRetrieveControllerTest.java
  src/test/java/com/liberty52/product/service/controller/ImageControllerTest.java
  src/test/java/com/liberty52/product/service/controller/ImageGenerationControllerTest.java
  src/test/java/com/liberty52/product/service/controller/ImageUpscalingControllerTest.java
  src/test/java/com/liberty52/product/service/controller/ReviewControllerTest.java
  src/test/java/com/liberty52/product/service/controller/ReviewReplyControllerTest.java
  src/test/java/com/liberty52/product/service/controller/ReviewReplyCreateControllerTest.java
  src/test/java/com/liberty52/product/service/controller/ReviewRetrieveControllerTest.java
Labels: 🔨 Refactor

#300 [관리자] 상품 추가
  build.gradle
  src/main/java/com/liberty52/product/global/config/BeanConfig.java
  src/main/java/com/liberty52/product/service/applicationservice/ProductCreateService.java
  src/main/java/com/liberty52/product/service/applicationservice/impl/ProductCreateServiceImpl.java
  src/main/java/com/liberty52/product/service/controller/ProductController.java
  src/main/java/com/liberty52/product/service/controller/ProductInfoController.java
  src/main/java/com/liberty52/product/service/controller/dto/ProductRequestDto.java
  src/main/java/com/liberty52/product/service/controller/dto/ProductResponseDto.java
  src/main/java/com/liberty52/product/service/entity/Product.java
  src/main/java/com/liberty52/product/service/entity/ProductState.java
  src/test/java/com/liberty52/product/service/applicationservice/mock/ProductCreateServiceMockTest.java
  src/test/java/com/liberty52/product/service/controller/ProductControllerTest.java
Labels: ✨ Feature, 🔗 API

#305 [관리자] 주문 상태 '배송시작'으로 변경 시 택배사 및 운송장번호 저장
  src/main/java/com/liberty52/product/global/adapter/courier/CourierCompanyClient.java
  src/main/java/com/liberty52/product/global/adapter/courier/api/smartcourier/SmartCourierCompanyClient.java
  src/main/java/com/liberty52/product/global/adapter/courier/api/smartcourier/dto/SmartCourierCompanyListDto.java
  src/main/java/com/liberty52/product/global/adapter/courier/api/smartcourier/dto/SmartCourierErrorDto.java
  src/main/java/com/liberty52/product/global/adapter/courier/config/SmartCourierConfig.java
  src/main/java/com/liberty52/product/global/adapter/courier/config/WebClientFactory.java
  src/main/java/com/liberty52/product/global/adapter/courier/util/UriUtil.java
  src/main/java/com/liberty52/product/global/exception/external/ErrorResponse.java
  src/main/java/com/liberty52/product/global/exception/external/RestExceptionHandler.java
  src/main/java/com/liberty52/product/service/applicationservice/OrderDeliveryService.java
  src/main/java/com/liberty52/product/service/applicationservice/impl/OrderDeliveryServiceImpl.java
  src/main/java/com/liberty52/product/service/controller/OrderAdminController.java
  src/main/java/com/liberty52/product/service/controller/dto/AdminAddOrderDeliveryDto.java
  src/main/java/com/liberty52/product/service/controller/dto/AdminCourierListDto.java
  src/main/java/com/liberty52/product/service/entity/OrderDelivery.java
  src/main/java/com/liberty52/product/service/entity/Orders.java
  src/test/java/com/liberty52/product/ProductApplicationTests.java
  src/test/java/com/liberty52/product/service/applicationservice/impl/OrderDeliveryServiceImplTest.java
  src/test/java/com/liberty52/product/service/controller/OrderAdminControllerTest.java
Labels: 🔗 API

#310 주문 정보 조회 시 주문배송정보(택배사코드, 택배사이름, 운송장번호) 반환 추가
  src/main/java/com/liberty52/product/service/applicationservice/impl/OrderRetrieveServiceImpl.java
  src/main/java/com/liberty52/product/service/controller/dto/AdminCanceledOrderListResponse.java
  src/main/java/com/liberty52/product/service/controller/dto/AdminOrderListResponse.java
  src/main/java/com/liberty52/product/service/controller/dto/OrderDeliveryDto.java
  src/main/java/com/liberty52/product/service/controller/dto/OrderDetailRetrieveResponse.java
  src/main/java/com/liberty52/product/service/controller/dto/OrdersRetrieveResponse.java
  src/main/java/com/liberty52/product/service/entity/Orders.java
  src/main/java/com/liberty52/product/service/repository/OrderQueryDslRepositoryImpl.java
  src/test/java/com/liberty52/product/service/applicationservice/impl/OrderRetrieveServiceImplTest.java
  src/test/java/com/liberty52/product/service/controller/OrderControllerTest.java
  src/test/java/com/liberty52/product/service/repository/OrdersTest.java
Labels: 🔗 API

#309 refactor: stable-diffusion, dalle, papago
  src/main/java/com/liberty52/product/global/adapter/DallEApiClient.java
  src/main/java/com/liberty52/product/global/adapter/ImageUpscaler.java
  src/main/java/com/liberty52/product/global/adapter/StableDiffusionApi.java
  src/main/java/com/liberty52/product/global/adapter/TextToImageGenerator.java
  src/main/java/com/liberty52/product/global/adapter/dalle/DallEApiClient.java
  src/main/java/com/liberty52/product/global/adapter/dalle/dto/DallEDto.java
  src/main/java/com/liberty52/product/global/adapter/dalle/error/DallEError.java
  src/main/java/com/liberty52/product/global/adapter/papago/PapagoApiClient.java
  src/main/java/com/liberty52/product/global/adapter/s3/S3UploaderImpl.java
  src/main/java/com/liberty52/product/global/adapter/stablediffusion/StableDiffusionClient.java
  src/main/java/com/liberty52/product/global/adapter/stablediffusion/dto/StableDiffusionResponse.java
  src/main/java/com/liberty52/product/global/adapter/stablediffusion/dto/SuperResolutionDto.java
  src/main/java/com/liberty52/product/global/adapter/stablediffusion/dto/TextToImageDto.java
  src/main/java/com/liberty52/product/global/adapter/stablediffusion/error/StableDiffusionError.java
  src/main/java/com/liberty52/product/global/util/Retries.java
  src/main/java/com/liberty52/product/service/applicationservice/impl/ImageGenerationServiceImpl.java
  src/main/java/com/liberty52/product/service/applicationservice/impl/ImageUpscalingServiceImpl.java
  src/main/java/com/liberty52/product/service/applicationservice/impl/TranslationServiceImpl.java
  src/test/java/com/liberty52/product/global/adapter/StableDiffusionClientTest.java
  src/test/java/com/liberty52/product/global/adapter/portone/webclient/DallEApiClientTest.java
  src/test/java/com/liberty52/product/global/adapter/portone/webclient/PapagoApiClientTest.java
  src/test/java/com/liberty52/product/service/applicationservice/impl/ImageUpscalingServiceImplTest.java
  src/test/java/com/liberty52/product/service/applicationservice/impl/TranslationServiceImplTest.java
Labels: 🔨 Refactor

#314 refactor: PortOne WebClient 빈 위치 변경
  src/main/java/com/liberty52/product/global/adapter/portone/PortOneRequestClient.java
  src/main/java/com/liberty52/product/global/adapter/portone/config/PortOneWebClientFactory.java
  src/main/java/com/liberty52/product/global/config/BeanConfig.java
  src/test/java/com/liberty52/product/ProductApplicationTests.java
Labels: 🔨 Refactor

#316 refactor: Main 클래스 configuration 어노테이션 분리
  src/main/java/com/liberty52/product/ProductApplication.java
  src/main/java/com/liberty52/product/global/config/FeignClientConfig.java
  src/main/java/com/liberty52/product/global/config/SchedulerConfig.java
Labels: 🔨 Refactor

#321 장바구니 상품 이름 --> 상품 ID
  src/main/java/com/liberty52/product/service/applicationservice/impl/CartItemCreateServiceImpl.java
  src/main/java/com/liberty52/product/service/controller/dto/CartItemRequest.java
  src/test/java/com/liberty52/product/service/applicationservice/CartItemCreateServiceTest.java
  src/test/java/com/liberty52/product/service/applicationservice/CartItemRetrieveServiceTest.java
  src/test/java/com/liberty52/product/service/applicationservice/CartItemSchedulerServiceTest.java
  src/test/java/com/liberty52/product/service/applicationservice/OrderCreateServiceByCartsTest.java
  src/test/java/com/liberty52/product/service/applicationservice/mock/CartItemCreateServiceMockTest.java
Labels: 🔨 Refactor

#317 [관리자] 상품 추가, 삭제 및 일부 설정 변경&추가
  lombok.config
  src/main/java/com/liberty52/product/global/annotation/validation/NullableNotBlank.java
  src/main/java/com/liberty52/product/global/annotation/validation/NullableNotBlankValidator.java
  src/main/java/com/liberty52/product/global/annotation/validation/NullableNotNegative.java
  src/main/java/com/liberty52/product/global/annotation/validation/NullableNotNegativeValidator.java
  src/main/java/com/liberty52/product/global/config/BeanConfig.java
  src/main/java/com/liberty52/product/service/applicationservice/ProductCreateService.java
  src/main/java/com/liberty52/product/service/applicationservice/ProductModifyService.java
  src/main/java/com/liberty52/product/service/applicationservice/ProductRemoveService.java
  src/main/java/com/liberty52/product/service/applicationservice/impl/ProductCreateServiceImpl.java
  src/main/java/com/liberty52/product/service/applicationservice/impl/ProductModifyServiceImpl.java
  src/main/java/com/liberty52/product/service/applicationservice/impl/ProductRemoveServiceImpl.java
  src/main/java/com/liberty52/product/service/controller/ProductController.java
  src/main/java/com/liberty52/product/service/controller/dto/ProductCreateRequestDto.java
  src/main/java/com/liberty52/product/service/controller/dto/ProductModifyRequestDto.java
  src/main/java/com/liberty52/product/service/controller/dto/ProductResponseDto.java
  src/main/java/com/liberty52/product/service/entity/Product.java
  src/test/java/com/liberty52/product/service/applicationservice/mock/ProductCreateServiceMockTest.java
  src/test/java/com/liberty52/product/service/applicationservice/mock/ProductModifyServiceMockTest.java
  src/test/java/com/liberty52/product/service/controller/ProductControllerTest.java
Labels: ✨ Feature, 🔗 API, 🔧 Build, 🔨 Refactor

#323 hotfix: Resolve merge conflict error
  src/main/java/com/liberty52/product/service/entity/Product.java
  src/test/java/com/liberty52/product/service/applicationservice/mock/ProductModifyServiceMockTest.java
Labels: 🐞 BugFix

#326 hotfix: 글자수제한 수정
  src/main/java/com/liberty52/product/service/entity/Product.java
  src/test/java/com/liberty52/product/service/applicationservice/ProductInfoRetrieveServiceTest.java
Labels: 🐞 BugFix

#334 hotfix: 주문배송정보 추가 시 중복추가 문제 해결
  src/main/java/com/liberty52/product/service/applicationservice/impl/OrderDeliveryServiceImpl.java
  src/main/java/com/liberty52/product/service/entity/OrderDelivery.java
  src/test/java/com/liberty52/product/service/applicationservice/impl/OrderDeliveryServiceImplTest.java
Labels: 🐞 BugFix

#335 [관리자] 상품별 택배사/배송비 관련 API 추가
  src/main/java/com/liberty52/product/service/applicationservice/ProductDeliveryOptionService.java
  src/main/java/com/liberty52/product/service/applicationservice/impl/ProductDeliveryOptionServiceImpl.java
  src/main/java/com/liberty52/product/service/controller/ProductInfoController.java
  src/main/java/com/liberty52/product/service/controller/dto/AdminProductDeliveryOptionsDto.java
  src/main/java/com/liberty52/product/service/entity/Product.java
  src/main/java/com/liberty52/product/service/entity/ProductDeliveryOption.java
  src/test/java/com/liberty52/product/service/applicationservice/impl/ProductDeliveryOptionServiceImplTest.java
  src/test/java/com/liberty52/product/service/controller/ProductInfoControllerTest.java
  src/test/java/com/liberty52/product/service/utils/MockFactory.java
Labels: ✨ Feature, 🔗 API

#337 [REFACTOR]제품 수정 테스트 메소드명 수정
  src/test/java/com/liberty52/product/service/applicationservice/mock/ProductModifyServiceMockTest.java
Labels: 🔨 Refactor

#342 상품, 라이선스 옵션 관계 변경 및 price 필드 추가
  src/main/java/com/liberty52/product/service/applicationservice/LicenseProductInfoRetrieveService.java
  src/main/java/com/liberty52/product/service/applicationservice/impl/LicenseOptionCreateServiceImpl.java
  src/main/java/com/liberty52/product/service/applicationservice/impl/LicenseOptionDetailCreateServiceImpl.java
  src/main/java/com/liberty52/product/service/applicationservice/impl/LicenseOptionModifyServiceImpl.java
  src/main/java/com/liberty52/product/service/applicationservice/impl/LicenseProductInfoRetrieveServiceImpl.java
  src/main/java/com/liberty52/product/service/controller/dto/LicenseOptionCreateRequestDto.java
  src/main/java/com/liberty52/product/service/controller/dto/LicenseOptionDetailCreateDto.java
  src/main/java/com/liberty52/product/service/controller/dto/LicenseOptionDetailModifyDto.java
  src/main/java/com/liberty52/product/service/controller/dto/LicenseOptionInfoResponseDto.java
  src/main/java/com/liberty52/product/service/controller/dto/LicenseOptionModifyRequestDto.java
  src/main/java/com/liberty52/product/service/controller/license/LicenseProductInfoController.java
  src/main/java/com/liberty52/product/service/entity/Product.java
  src/main/java/com/liberty52/product/service/entity/license/LicenseOption.java
  src/main/java/com/liberty52/product/service/entity/license/LicenseOptionDetail.java
  src/test/java/com/liberty52/product/service/applicationservice/mock/LicenseOptionCreateMockTest.java
  src/test/java/com/liberty52/product/service/applicationservice/mock/LicenseOptionDetailCreateMockTest.java
  src/test/java/com/liberty52/product/service/applicationservice/mock/LicenseOptionDetailModifyMockTest.java
  src/test/java/com/liberty52/product/service/applicationservice/mock/LicenseOptionModifyMockTest.java
  src/test/java/com/liberty52/product/service/applicationservice/mock/LicenseProductInfoRetrieveMockTest.java
Labels: 🔗 API
